name: Static Map Maker
description: "Create a Bing static map, Google static map, Mapbox static map, or MapQuest static map with Static Map Maker. Type in a location, customize, and get the map."
url: http://staticmapmaker.com
permalink: pretty

apis:
- Bing
- Google
- Mapbox
- MapQuest

port: 4000
host: 127.0.0.1

# these will rotate
mapquestKey: Fmjtd%7Cluu8296rn5%2C8x%3Do5-9w1ld6
bingKey: Ag5uuxO0xffGEd9QQ5vIaOp_f1KlwIycTPD4dLaYGHdfwkr5QP-lTIXwZE-_2oos

exclude: ["node_modules", ".sass-cache","package.json","Gruntfile.js"]

gems:
- jekyll-sitemap
- jekyll-redirect-from
- jemoji

angularjs: 1.3.8
jquery: 2.1.3
