name: Static Map Maker
description: "Create a Google static map or Mapbox static map with Static Map Maker. Type in a location, customize, and get the map."
url: http://staticmapmaker.com
permalink: pretty

mapboxAPI: https://www.mapbox.com/developers/api/static/
googleAPI: https://developers.google.com/maps/documentation/staticmaps/
mapquetAPI: http://www.mapquestapi.com/staticmap/




mapquestAPI: Fmjtd%7Cluu8296rn5%2C8x%3Do5-9w1ld6

exclude: ["node_modules", ".sass-cache","package.json","Gruntfile.js"]

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

angularjs: 1.3.8
jquery: 2.1.3
