name: Static Map Maker
markdown: redcarpet
highlighter: pygments
description: "Need a static map? You got it. Type in a location, customize, and get the map using Google or Mapbox."
url: "http://staticmapmaker.com"
permalink: pretty

mapboxAPI: https://www.mapbox.com/developers/api/static/
googleAPI: https://developers.google.com/maps/documentation/staticmaps/

exclude: ["node_modules", ".sass-cache","package.json","Gruntfile.js"]
